version: '3.8'

services:
  # 数据库服务 (MariaDB) - 使用官方镜像
  mariadb:
    image: mariadb:11.3
    container_name: opt-mariadb-1
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-default_password}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-wordpress}
      - MARIADB_USER=${MARIADB_USER:-wordpress}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-default_password}
    healthcheck:
      test: ["CMD", "timeout", "1", "bash", "-c", "cat < /dev/null > /dev/tcp/localhost/3306"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app-network
    restart: always

  # Redis 缓存服务 - 使用官方镜像
  redis:
    image: redis:7.4
    container_name: opt-redis-1
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    restart: always

  # --- PHP-FPM 服务 ---
  php:
    # 构建配置（用于GitHub Actions）
    build:
      context: .
      dockerfile: build/Dockerfiles/php/Dockerfile
    image: chisenin/wordpress-php:8.3.26
    # 注意：此配置仅用于构建参考，生产环境配置由auto_deploy.sh脚本生成
    networks:
      - app-network
    volumes:
      - ./html:/var/www/html
      - ./build/deploy_configs/php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      # 构建参考环境变量，生产环境将使用随机生成的值
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: build_reference_only
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_REDIS_PORT: 6379
      PHP_OPCACHE_ENABLE: 1
      PHP_MEMORY_LIMIT: 512M

  # --- Nginx 服务 ---
  nginx:
    # 构建配置（用于GitHub Actions）
    build:
      context: .
      dockerfile: build/Dockerfiles/nginx/Dockerfile
    image: chisenin/wordpress-nginx:1.27.2
    # 注意：此配置仅用于构建参考，生产环境配置由auto_deploy.sh脚本生成
    networks:
      - app-network
    volumes:
      # 映射自定义配置文件
      - ./build/deploy_configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/deploy_configs/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./html:/var/www/html

networks:
  app-network:
    driver: bridge

# 注意：此docker-compose.yml仅用于GitHub Actions构建参考
# 生产环境中，auto_deploy.sh脚本会根据服务器实际情况生成完整配置
# Windows本地环境不需要使用此文件运行服务
