version: '3.8'

services:
  # --- MariaDB 数据库服务 ---
  db:
    image: mariadb:10.11.6 # 使用固定的稳定版本号
    container_name: wp_db
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: your_strong_user_password
    expose:
      - "3306"

  # --- Redis 缓存服务 ---
  redis:
    image: redis:7.2.4-alpine3.20 # 使用固定版本号，并注明基础系统版本
    container_name: wp_redis
    restart: unless-stopped
    networks:
      - app-network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - "6379"

  # --- PHP-FPM 服务 ---
  wp:
    image: ${DOCKERHUB_USERNAME:-chisenin}/wordpress-php:8.3  # <--- 从 Docker Hub 拉取自定义镜像（使用环境变量，默认值为chisenin；实际标签为动态提取的 8.3.x 版本）
    # build:  # 开发时启用
    #   context: ./Dockerfiles/php
    #   dockerfile: Dockerfile
    container_name: wp_fpm
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      # 注意：宿主机 html 目录挂载到容器内 /var/www/html
      - ./html:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
      - redis
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: your_strong_user_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_REDIS_PORT: 6379

  # --- Nginx 服务 ---
  nginx:
    image: ${DOCKERHUB_USERNAME:-chisenin}/wordpress-nginx:1.27  # <--- 从 Docker Hub 拉取自定义镜像（使用环境变量，默认值为chisenin；实际标签为动态提取的 1.27.x 版本）
    # build:  # 开发时启用
    #   context: ./Dockerfiles/nginx
    #   dockerfile: Dockerfile
    container_name: wp_nginx
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      # 挂载自定义配置文件，使用统一的 configs 目录
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - wp

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  redis_data: