version: '3.8'

services:
  # --- MariaDB 数据库服务 ---
  mariadb:
    image: mariadb:10.11.14 # 使用固定的稳定版本号
    container_name: wp_db
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"

  # --- Redis 缓存服务 ---
  redis:
    image: redis:8.2.2-alpine3.22 # 使用固定的基于Alpine 3.22的版本
    container_name: wp_redis
    restart: unless-stopped
    networks:
      - app-network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - "6379"

  # --- PHP-FPM 服务 ---
  php:
    # 使用官方PHP-FPM镜像作为后备选项
    build:
      context: .
      dockerfile: build/Dockerfiles/php/Dockerfile
    image: ${DOCKERHUB_USERNAME:-library}/wordpress-php:${PHP_VERSION:-8.3-fpm-alpine3.22}  # 为环境变量提供默认值
    container_name: wp_fpm
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      # 注意：宿主机 html 目录挂载到容器内 /var/www/html
      - ./html:/var/www/html
      # 使用deploy目录中的PHP配置
      - ./deploy/configs/php.ini:/usr/local/etc/php/php.ini:ro
    expose:
      - "9000"
    depends_on:
      - mariadb
      - redis
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_REDIS_PORT: 6379

  # --- Nginx 服务 ---
  nginx:
    # 使用官方Nginx镜像作为后备选项
    build:
      context: .
      dockerfile: build/Dockerfiles/nginx/Dockerfile
    image: ${DOCKERHUB_USERNAME:-library}/wordpress-nginx:${NGINX_VERSION:-1.27-alpine}  # 为环境变量提供默认值
    container_name: wp_nginx
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      # 挂载自定义配置文件，使用build目录中的配置
      - ./build/Dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/Dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  redis_data: