version: '3.8'

services:
  # --- MariaDB 数据库服务 ---
  mariadb:
    # 使用我们构建的MariaDB镜像，支持自动更新
    build:
      context: .
      dockerfile: build/Dockerfiles/mariadb/Dockerfile
    image: chisenin/wordpress-mariadb:11.3.2
    container_name: wp_db
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
      - ./build/deploy_configs/mariadb/my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEMORY_LIMIT:-1G}

  # --- Redis 缓存服务 ---
  redis:
    # 使用我们构建的Redis镜像，支持自动更新
    build:
      context: .
      dockerfile: build/Dockerfiles/redis/Dockerfile
    image: chisenin/wordpress-redis:7.4.0
    container_name: wp_redis
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - redis_data:/data
      - ./build/deploy_configs/redis/redis.conf:/etc/redis/redis.conf:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_MAXMEMORY: ${REDIS_MAXMEMORY:-256mb}
    expose:
      - "6379"
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD:-}', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

  # --- PHP-FPM 服务 ---
  php:
    # 使用我们构建的PHP镜像，支持自动更新
    build:
      context: .
      dockerfile: build/Dockerfiles/php/Dockerfile
    image: chisenin/wordpress-php:8.3.26
    container_name: wp_fpm
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      # 注意：主机html目录映射到容器内/var/www/html
      - ./html:/var/www/html
      # 使用deploy目录中的PHP配置
      - ./build/deploy_configs/php/php.ini:/usr/local/etc/php/php.ini:ro
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_REDIS_PORT: 6379
      PHP_OPCACHE_ENABLE: 1
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEMORY_LIMIT:-512M}

  # --- Nginx 服务 ---
  nginx:
    # 使用我们构建的Nginx镜像，支持自动更新
    build:
      context: .
      dockerfile: build/Dockerfiles/nginx/Dockerfile
    image: chisenin/wordpress-nginx:1.27.2
    container_name: wp_nginx
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      # 映射自定义配置文件
      - ./build/deploy_configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/deploy_configs/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./html:/var/www/html
      - nginx_logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      php:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEMORY_LIMIT:-512M}

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local
