name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 版本监控（暂关闭，待测试）
  # check-versions:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     trigger_build: ${{ steps.check.outputs.trigger_build }}
  #     php_version: ${{ steps.check.outputs.php_version }}
  #     nginx_version: ${{ steps.check.outputs.nginx_version }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Install skopeo and jq
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y skopeo jq
  #     - name: Run version check script
  #       id: check
  #       run: |
  #         chmod +x scripts/check_versions.sh
  #         ./scripts/check_versions.sh
  #     - name: Upload versions artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: versions
  #         path: versions.json

  build:
    # needs: check-versions
    # if: needs.check-versions.outputs.trigger_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Create scripts directory
        run: mkdir -p scripts

      # 构建 base 镜像并推送（支持多架构）
      - name: Build and push base image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -f ./Dockerfiles/base/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-base:3.22 \
            --push ./Dockerfiles/base

      # 获取 Composer hash
      - name: Fetch Composer hash
        run: |
          COMPOSER_HASH=$(curl -s https://composer.github.io/installer.sig || echo "")
          echo "COMPOSER_HASH=$COMPOSER_HASH" >> $GITHUB_ENV

      # 提取 PHP 和 Nginx 版本号
      - name: Extract PHP and Nginx versions
        id: extract
        run: |
          # 尝试从文件获取，如果文件不存在则使用默认值
          echo "php_version=$(cat Dockerfiles/php/php_version.txt || echo '8.3.26')" >> $GITHUB_OUTPUT
          echo "nginx_version=$(cat Dockerfiles/nginx/nginx_version.txt || echo '1.27.2')" >> $GITHUB_OUTPUT
          
          # 同时设置为环境变量便于后续使用
          echo "PHP_VERSION=$(cat Dockerfiles/php/php_version.txt || echo '8.3.26')" >> $GITHUB_ENV
          echo "NGINX_VERSION=$(cat Dockerfiles/nginx/nginx_version.txt || echo '1.27.2')" >> $GITHUB_ENV
          
          # 如果版本文件不存在，创建它们
          if [ ! -f Dockerfiles/php/php_version.txt ]; then
            echo "8.3.26" > Dockerfiles/php/php_version.txt
          fi
          if [ ! -f Dockerfiles/nginx/nginx_version.txt ]; then
            echo "1.27.2" > Dockerfiles/nginx/nginx_version.txt
          fi

      # 构建 PHP 镜像并推送
      - name: Build and push PHP image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/wordpress-base:3.22 \
            --build-arg COMPOSER_HASH=${{ env.COMPOSER_HASH }} \
            -f ./Dockerfiles/php/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:${{ steps.extract.outputs.php_version }} \
            --push ./Dockerfiles/php
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      # 构建 Nginx 镜像并推送
      - name: Build and push Nginx image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/wordpress-base:3.22 \
            -f ./Dockerfiles/nginx/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:${{ steps.extract.outputs.nginx_version }} \
            --push ./Dockerfiles/nginx

      # Release 脚本（暂关闭，待测试）
      # - name: Create deployment script
      #   run: |
      #     cat > scripts/generate-env-and-compose.sh << 'EOF'
      #     #!/bin/bash
      #     echo "Generating .env and docker-compose.yml..."
      #     cat > .env << EOT
      #     DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
      #     PHP_VERSION=${{ steps.php-build.outputs.php_version }}
      #     NGINX_VERSION=${{ steps.nginx-build.outputs.nginx_version }}
      #     MYSQL_ROOT_PASSWORD=your_strong_root_password
      #     MYSQL_USER=wp_user
      #     MYSQL_PASSWORD=your_strong_user_password
      #     MYSQL_DATABASE=wordpress
      #     EOT
      #     cat > docker-compose.yml << EOT
      #     version: '3.8'
      #     services:
      #       db:
      #         image: mariadb:10.11.14
      #         container_name: wp_db
      #         restart: unless-stopped
      #         networks:
      #           - app-network
      #         volumes:
      #           - db_data:/var/lib/mysql
      #         environment:
      #           MYSQL_ROOT_PASSWORD: \${MYSQL_ROOT_PASSWORD}
      #           MYSQL_DATABASE: \${MYSQL_DATABASE}
      #           MYSQL_USER: \${MYSQL_USER}
      #           MYSQL_PASSWORD: \${MYSQL_PASSWORD}
      #         expose:
      #           - "3306"
      #       redis:
      #         image: redis:8.2.2-alpine3.22
      #         container_name: wp_redis
      #         restart: unless-stopped
      #         networks:
      #           - app-network
      #         command: redis-server --appendonly yes
      #         volumes:
      #           - redis_data:/data
      #         expose:
      #           - "6379"
      #       wp:
      #         image: \${DOCKERHUB_USERNAME}/wordpress-php:\${PHP_VERSION}
      #         container_name: wp_fpm
      #         restart: unless-stopped
      #         networks:
      #           - app-network
      #         volumes:
      #           - ./html:/var/www/html
      #         expose:
      #           - "9000"
      #         depends_on:
      #           - db
      #           - redis
      #         environment:
      #           WORDPRESS_DB_HOST: db:3306
      #           WORDPRESS_DB_USER: \${MYSQL_USER}
      #           WORDPRESS_DB_PASSWORD: \${MYSQL_PASSWORD}
      #           WORDPRESS_DB_NAME: \${MYSQL_DATABASE}
      #           WORDPRESS_REDIS_HOST: redis
      #           WORDPRESS_REDIS_PORT: 6379
      #       nginx:
      #         image: \${DOCKERHUB_USERNAME}/wordpress-nginx:\${NGINX_VERSION}
      #         container_name: wp_nginx
      #         restart: unless-stopped
      #         networks:
      #           - app-network
      #         volumes:
      #           - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      #           - ./configs/nginx/conf.d:/etc/nginx/conf.d
      #           - ./html:/var/www/html
      #         ports:
      #           - "80:80"
      #         depends_on:
      #           - wp
      #     networks:
      #       app-network:
      #         driver: bridge
      #     volumes:
      #       db_data:
      #       redis_data:
      #     EOT
      #     echo "Generated .env and docker-compose.yml"
      #     EOF
      #     chmod +x scripts/generate-env-and-compose.sh
      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: v${{ github.sha }}
      #     name: Release with PHP ${{ steps.php-build.outputs.php_version }} and Nginx ${{ steps.nginx-build.outputs.nginx_version }}
      #     body: Built with PHP ${{ steps.php-build.outputs.php_version }} and Nginx ${{ steps.nginx-build.outputs.nginx_version }}
      #     files: |
      #       scripts/generate-env-and-compose.sh

      - name: Run docker compose for validation (optional)
        run: |
          docker compose up -d
          sleep 10
          curl -f http://localhost || exit 1
          docker compose down