name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build PHP image (temp)
      id: php-build
      uses: docker/build-push-action@v6
      with:
        context: ./Dockerfiles/php
        file: ./Dockerfiles/php/Dockerfile
        push: false
        load: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:temp
        platforms: linux/amd64,linux/arm64
        build-args: |
          USE_CN_MIRROR=false
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Extract PHP version and push
      run: |
        ACTUAL_PHP_VERSION=$(docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:temp cat /tmp/php_version)
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:temp ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:${ACTUAL_PHP_VERSION}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:temp ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:${ACTUAL_PHP_VERSION}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:latest
        echo "php_version=${ACTUAL_PHP_VERSION}" >> $GITHUB_OUTPUT

    - name: Verify Nginx base image exists
      run: docker pull nginx:1.27-alpine3.20

    - name: Build Nginx image (temp)
      id: nginx-build
      uses: docker/build-push-action@v6
      with:
        context: ./Dockerfiles/nginx
        file: ./Dockerfiles/nginx/Dockerfile
        push: false
        load: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:temp
        platforms: linux/amd64,linux/arm64
        build-args: |
          USE_CN_MIRROR=false
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Extract Nginx version and push
      run: |
        ACTUAL_NGINX_VERSION=$(docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:temp cat /tmp/nginx_version)
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:temp ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:${ACTUAL_NGINX_VERSION}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:temp ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:${ACTUAL_NGINX_VERSION}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:latest
        echo "nginx_version=${ACTUAL_NGINX_VERSION}" >> $GITHUB_OUTPUT

    - name: Run docker-compose for validation (optional)
      run: |
        docker-compose up -d --build
        sleep 10
        curl -f http://localhost || exit 1
        docker-compose down