name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push PHP image
      uses: docker/build-push-action@v6
      with:
        context: ./Dockerfiles/php
        file: ./Dockerfiles/php/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:8.2.12
          ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify Nginx base image exists
      run: docker pull nginx:1.25.4-alpine3.18
    
    - name: Build and push Nginx image
      uses: docker/build-push-action@v6
      with:
        context: ./Dockerfiles/nginx
        file: ./Dockerfiles/nginx/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:1.25.4
          ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run docker-compose for validation (optional)
      run: |
        docker-compose up -d --build
        sleep 10
        curl -f http://localhost || exit 1
        docker-compose down