name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送 Base 镜像
        run: |
          echo "::group::构建并推送 Base 镜像"
          docker buildx build --platform linux/amd64,linux/arm64 \
            -f ./Dockerfiles/base/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-base:3.22 \
            --push ./Dockerfiles/base > /dev/null 2>&1 || {
              echo "::error::构建或推送 base 镜像失败"
              exit 1
            }
          echo "::endgroup::"

      - name: 提取 PHP 和 Nginx 版本
        id: extract
        run: |
          echo "::group::提取版本"
          PHP_VERSION=$(cat Dockerfiles/php/php_version.txt 2>/dev/null || echo '8.3.26')
          NGINX_VERSION=$(cat Dockerfiles/nginx/nginx_version.txt 2>/dev/null || echo '1.27.2')

          [ ! -f Dockerfiles/php/php_version.txt ] && echo "::warning::PHP 版本文件缺失，默认使用 $PHP_VERSION"
          [ ! -f Dockerfiles/nginx/nginx_version.txt ] && echo "::warning::Nginx 版本文件缺失，默认使用 $NGINX_VERSION"

          echo "php_version=$PHP_VERSION" >> $GITHUB_OUTPUT
          echo "nginx_version=$NGINX_VERSION" >> $GITHUB_OUTPUT
          echo "PHP_VERSION=$PHP_VERSION" >> $GITHUB_ENV
          echo "NGINX_VERSION=$NGINX_VERSION" >> $GITHUB_ENV
          echo "::endgroup::"

      - name: 构建并推送 PHP 镜像
        run: |
          echo "::group::构建并推送 PHP 镜像"
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/wordpress-base:3.22 \
            --build-arg COMPOSER_HASH=55ce33d7678c5a611085731c9a2ba383d4d23389a81006900a0a43ed373ded6a0ee64936d3ab3d8e444a3e7a120dd6d57b55955475e363fbeefa16e7d97b7c0 \
            -f ./Dockerfiles/php/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-php:${{ steps.extract.outputs.php_version }} \
            --push . > /dev/null 2>&1 || {
              echo "::error::构建或推送 PHP 镜像失败"
              exit 1
            }
          echo "::endgroup::"

      - name: 构建并推送 Nginx 镜像
        run: |
          echo "::group::构建并推送 Nginx 镜像"
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/wordpress-base:3.22 \
            --build-arg NGINX_VERSION=${{ steps.extract.outputs.nginx_version }} \
            -f ./Dockerfiles/nginx/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-nginx:${{ steps.extract.outputs.nginx_version }} \
            --push . 
          echo "::endgroup::"

      - name: Docker Compose 验证（可选）
        run: |
          echo "::group::Docker Compose 验证"

          if [ ! -f docker-compose.yml ]; then
            echo "::error::docker-compose.yml 文件缺失"
            exit 1
          fi

          docker compose --project-directory . up -d > /dev/null 2>&1 || {
            echo "::error::Docker Compose 启动失败"
            exit 1
          }

          sleep 10

          curl -f --connect-timeout 5 --retry 3 http://localhost > /dev/null 2>&1 || {
            echo "::error::服务连通性测试失败"
            docker compose logs || true
            docker compose down || true
            exit 1
          }

          docker compose down > /dev/null 2>&1 || {
            echo "::warning::Docker Compose 停止失败"
          }

          echo "::endgroup::"